//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("PhoneShell.Core")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.4.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.4.0+67d6fe5e05d9237a77beb76ebc331a0ebf94a28b")]
[assembly: System.Reflection.AssemblyProductAttribute("PhoneShell.Core")]
[assembly: System.Reflection.AssemblyTitleAttribute("PhoneShell.Core")]
[assembly: System.Reflection.AssemblyVersionAttribute("0.4.0.0")]

// 由 MSBuild WriteCodeFragment 类生成。

